### ISSUE TITLE
what should final output be for Windows?

### ISSUE THREAD

**Issue by jden** [maxogden/electron-packager#21]
Mac apps are conveniently distributed as folders, and the OS GUI treats them nicely as a single entity. On Windows (with #20) we end up as a folder, which is not a very natural way to distribute apps.

There's a couple of options I wanted to raise for discussion:

0) do nothing: we end up with a working folder, and anything else is out of scope of this module and should be handled elsewhere
1) zip the folder: this is a sort of bare minimum, and a fair number of smaller windows apps are distributed this way. We get a single file to distribute e.g. in a GitHub release, archive, etc. Zip is the idiomatic archive format for Windows.
2) create an msi: this is the Windows native installer bundler format- e.g., how io.js is distributed, as well as almost all commerical apps. This has the most polish. There are [a billion options](https://msdn.microsoft.com/en-us/library/aa372463(v=vs.85).aspx) with msis, but it should be possible to create a generic one that plays nicely with Electron apps and puts them in platform-idiomatic places, etc.

**Comment by maxogden** [comment]
atom has both a `AtomSetup.exe` and a `atom-windows.zip`. Im on slow internet and cant download both to check em out, but I wonder what the diff is

https://github.com/atom/atom/releases/tag/v0.196.0

**Comment by marwanhilmi** [comment]
```atom-windows.zip``` is a simply a .zip of the output folder as described in Option 1.
```AtomSetup.exe``` is an installer created with [Squirrel for Windows](https://github.com/Squirrel/Squirrel.Windows) which does a few things:
- installs to user's home directory in AppData/Local
- creates entry in Add/Remove programs
- allows for auto-updating to work (whereas the zip version does not support it)

Naturally the simple option is .zip support.

It is also pretty straight forward to create a basic installer with a MakeNSIS configuration file (see example here: https://github.com/Aluxian/Facebook-Messenger-Desktop/blob/master/assets-windows/) but note that wouldn't give the auto-updating functionality found in the solution Atom uses.

My current use case calls for using Squirrel (because I need the auto-updater and don't want to roll my own). We would need to either bundle or download a handful of the Squirrel binaries. You can see how Atom uses Squirrel to generate the installer here: https://github.com/atom/grunt-electron-installer

**Comment by maxogden** [comment]
is the .zip in option 1 a zip that has e.g. `App.exe` inside it that users can double click to run the app? If so I think thats a good place to start (since it is the simplest option)

**Comment by marwanhilmi** [comment]
Yeah that's what it looks like, an exe file along with a handful of other dlls and misc files.
```
-rwxr-xr-x@   1 mhilmi  staff      1055 Apr 30 20:42 LICENSE
-rwxr-xr-x@   1 mhilmi  staff   1492992 Apr 30 20:44 Update.exe
-rwxr-xr-x@   1 mhilmi  staff   7214344 Apr 30 20:46 atom.exe
drwxr-xr-x@   4 mhilmi  staff       136 Apr 30 20:42 chromedriver
-rwxr-xr-x@   1 mhilmi  staff  56402432 Apr 30 20:42 chromiumcontent.dll
-rwxr-xr-x@   1 mhilmi  staff    252859 Apr 30 20:42 content_resources_200_percent.pak
-rwxr-xr-x@   1 mhilmi  staff   8457212 Apr 30 20:42 content_shell.pak
-rwxr-xr-x@   1 mhilmi  staff   3466856 Apr 30 20:42 d3dcompiler_47.dll
-rwxr-xr-x@   1 mhilmi  staff   1686016 Apr 30 20:42 ffmpegsumo.dll
-rwxr-xr-x@   1 mhilmi  staff  10457856 Apr 30 20:42 icudtl.dat
-rwxr-xr-x@   1 mhilmi  staff     10752 Apr 30 20:42 libEGL.dll
-rwxr-xr-x@   1 mhilmi  staff   1512960 Apr 30 20:42 libGLESv2.dll
drwxr-xr-x@  55 mhilmi  staff      1870 Apr 30 20:42 locales
-rwxr-xr-x@   1 mhilmi  staff    455328 Apr 30 20:42 msvcp120.dll
-rwxr-xr-x@   1 mhilmi  staff    970912 Apr 30 20:42 msvcr120.dll
-rwxr-xr-x@   1 mhilmi  staff    413533 Apr 30 20:42 natives_blob.bin
drwxr-xr-x@   8 mhilmi  staff       272 Apr 30 20:44 resources
-rwxr-xr-x@   1 mhilmi  staff    742500 Apr 30 20:42 snapshot_blob.bin
-rwxr-xr-x@   1 mhilmi  staff    199302 Apr 30 20:42 ui_resources_200_percent.pak
-rwxr-xr-x@   1 mhilmi  staff    247984 Apr 30 20:42 vccorlib120.dll
-rwxr-xr-x@   1 mhilmi  staff         7 Apr 30 20:42 version
-rwxr-xr-x@   1 mhilmi  staff     81768 Apr 30 20:42 xinput1_3.dll
```

**Comment by jden** [comment]
In the zip option, users would have to unzip it to a directory somewhere and then run the .exe from that location

**Comment by Ivshti** [comment]
I am for an option between zip and raw folder. An installer doesn't make sense, I think it's out of the scope for electron-packager. Maybe a new tool that creates an installer for Windows and a dmg for OS X?

**Comment by maxogden** [comment]
@Ivshti +1 that is a great point about scope

**Comment by englercj** [comment]
Just to throw in my two cents, I'm using this for creating packages currently and I love it.

I agree with @Ivshti that installers are out of scope of this tool, but the only tool I am aware of (https://github.com/domderen/atom-shell-installer) doesn't work with a folder output from this tool (some complaint about name in the nuget packing process). So really looking for a CLI tool like this one that can create installer/dmg files for these apps for distribution.

**Comment by Ivshti** [comment]
@englercj this is a tough thing. I've been packaging my app for almost a year now, and there are a few challenges I couldn't automate

1) DMG - setting OS X folder options for a background and icon size programatically; couldn't find a way to do that. You can still use a template DMG and build from there

2) Windows - finding a quality self-extracting installer that allows building from any platform (I Use OS X for building / dev); Paquet Builder is terrific but also paid (IMO deservingly so) and can be used programatically. Unfortunately I don't know if Wine can run it so that we can build from any platform.

My 2 cents, unless you're pushing new versions out every day, do the final step manually. It takes like 3 actions on OS X (replacing .app in the DMG) and 2-3 on Windows (pressing build on your installer creator). 

I am not trying to discourage you from automation though, I am just saying it's a nasty process to automate. For OS X - sure. For windows - if there's a way to build quality SFX installers under any platform - sure, but I haven't been able to find that.

**Comment by jden** [comment]
@englercj 
> atom-shell-installer doesn't work with a folder output from this tool 

Could you please open an issue and include the specific error message? Thanks!

**Comment by maxogden** [comment]
thanks for the feedback everyone, I'm gonna close this for now but open a new issue to specifically discuss app packaging

**Comment by maxogden** [comment]
ok new issue to discuss installers is here: https://github.com/maxogden/electron-packager/issues/33

**Comment by lmatteis** [comment]
@Ivshti how do you actually "press build on your installer creator"? Where do you find this option? I'd like to deliver a single .exe rather than a .zip with a bunch of dll's inside.
