### ISSUE TITLE
Infer from package.json

### ISSUE THREAD

**Issue by sindresorhus** [maxogden/electron-packager#37]
Would be useful if it could infer the name from the `name` field in package.json (titelized) and the `--version` from the "electron-prebuilt" dependency. This to reduce config and not requiring to define this in multiple places. This is just default and users could just override as normal with the cli arguments.

**Comment by sbruchmann** [comment]
There’s also [`productName`](https://github.com/atom/electron/blob/f02cae1b0ab60824f76dfdfb13732edee5924eae/docs/api/app.md#appgetname), which is a bit more suitable for this task.

**Comment by sindresorhus** [comment]
Yes, indeed.

**Comment by klaemo** [comment]
app-version could be inferred from the package.json `version` field as well, I think. That way building a correctly version app would be as simple as `npm version patch|minor|major && npm run build` (assuming npm run build does the right thing).

**Comment by rahatarmanahmed** [comment]
+1, I might take a stab at this. Should it check for `package.json` in the cwd?

**Comment by kfranqueiro** [comment]
I think searching upwards seems like a good plan regardless, but here are a couple of off-the-cuff ideas in terms of where to start searching:

* Start with `opts.dir` and look upwards, since there may be a package.json there (e.g. to specify main)
  * Possible disadvantage is if you have a more fully-populated package.json higher up your tree
* Start from `../..` relative to `__dirname` of electron-packager's main modules - this would likely coincide with `process.cwd()` in common cases, but wouldn't break if people ran it from elsewhere

My brain cells are limited at the moment so feel free to point out if I am overlooking something dumb :)

**Comment by rahatarmanahmed** [comment]
A good way to avoid the problem in the first way is to keep looking in higher in the tree if the first package.json you find doesn't have an `electron-prebuilt`.

**Comment by Mingling94** [comment]
Request: This should infer to package the `dependencies` but not the `devDependencies`

**Comment by rahatarmanahmed** [comment]
Do you mean to include `dependencies` in the build or to use the `electron-prebuilt` version in `dependencies`?

**Comment by Mingling94** [comment]
^The former, not your pr.

`dependencies` mean the electron app *needs* the package to run, right? `devDependencies` are not needed. If one uses the package.json as per npm philosophy, ALL the `dependencies` should be in `node_modules` and included in the packaged product.

**gets off soapbox**

**Comment by rahatarmanahmed** [comment]
We already have `--prune`, so if `node_modules` is in your src path, you can use that to ignore `devDependencies`.

**Comment by Mingling94** [comment]
Ah, I see!
