### ISSUE TITLE
--all option

### ISSUE THREAD

**Issue by maxogden** [maxogden/electron-packager#40]
if you pass `--all` it should compile all possible combinations of arch and platform (that make sense)

**Comment by sindresorhus** [comment]
:+1: Hah, I was just about to open an issue about this.

**Comment by jden** [comment]
It would be great to do these multiple builds in parallel, too!

**Comment by Flet** [comment]
Wrote this for `friends` which accomplishes this via `shelljs`:
https://github.com/moose-team/friends/blob/master/pkg.js

 But I too came here to see if it made sense to add a build all flag here or to do it in a higher level module.

**Comment by mixmatch** [comment]
Related to this is an issue i experienced recently, packaged for one platform, then another and the first platform package folder was included in the next package platform...would be nice if default 'out' was inside of a dist folder that is ignored by default when packaging...

**Comment by Flet** [comment]
Indeed, this is also reflected in the `pkg.js` script above :)
```
' --ignore=pkg' // ignore the pkg directory or hilarity will ensue
```

**Comment by mixmatch** [comment]
Somehow missed your script Flet. Thanks!

**Comment by kfranqueiro** [comment]
It occurs to me that we'd have to answer the question regarding how to structure subfolders to accommodate this, as has been discussed on #38.

Currently, electron-packager already effectively creates one level of subfolder with the OS name for Windows (and inconsistently only if `--out` is *not* specified for Linux).  Mac only gets a "subfolder" by virtue of how `.app`s are structured to begin with.

I would be inclined to suggest always packaging into a `name-<os>-<arch>` subfolder (even for Mac - the `.app` would be inside that folder).  This has the following benefits:

* Always follows the same pattern whether `--all` is specified or not
* Isn't too onerous in cases where `--all` is not specified (as opposed to `os/arch/name` or `os-arch/name` - the subdirectories would seem kind of silly if you're only building for one at a time)
* Never risks dumping a ton of files into the current directory or a parent directory of what the user expected

Meanwhile, how about also supporting `--platform=all`, so you could build for all platforms but only one arch if you wanted?  (I presume `--all` would build all platforms for all architectures.)

**Comment by kfranqueiro** [comment]
FYI I started working on implementing this: https://github.com/kfranqueiro/electron-packager/commits/all

Ensuring unique directories per-architecture isn't done yet.

It uses `run-series`, so it doesn't run in parallel as someone here suggested; that could potentially be arranged if we used `run-parallel` I suppose, but I'm wary of doing that primarily because I suspect it'd throw a wrench in the works of `electron-download` output.

**Comment by kfranqueiro** [comment]
It occurs to me that `--all` might be incompatible with `--icon` as it is currently implemented, since AFAIK Windows and OS X accept different icon formats.  I suppose we might be able to get around that by taking the basename of whatever's passed and looking for `.icns` and `.ico` for each respective platform...
