### ISSUE TITLE
Cannot create symlinks; skipping darwin platform on Windows

### ISSUE THREAD

**Issue by s-a** [maxogden/electron-packager#96]
- ```v5.0.0```
 - ```npm run clean:osx && electron-packager ./app \"sulu\" --out=dist --platform=darwin --arch=x64 --version=0.25.3 --icon=src/icon.icns```
 - ```windows 7 32bit```  

Returns ```Cannot create symlinks; skipping darwin platform``` :crying_cat_face:

**Comment by kfranqueiro** [comment]
That message is due to electron-packager working around #71 (which I see you've also commented on); without the workaround, electron-packager would just silently bail out in this situation.

You can try running as administrator on Windows to get around this, but even then, I'm not sure there's a safe way to zip up the OS X app - I tried Windows' built-in compressed folder and 7-zip and both trip up on the symlinks.

I'm inclined to close this and continue tracking #71.

**Comment by s-a** [comment]
It works running cmd.exe as admin. Strange. I am always logged in as administrator! Anyway ty for help!

**Comment by kfranqueiro** [comment]
No problem.  I'll close this then.

**Comment by s-a** [comment]
Just in case any one else having trouble to copy symlinks on windows for :apple:  distribution 

```xcopy /b /Y /E . c:\dist-osx\```

**Comment by s-a** [comment]
@kfranqueiro you are right. Far away from easy to distribute. Cannot zip and cannot add symlinks to git repo :/

**Comment by toolness** [comment]
Another option here is to use Docker with a named volume, which is essentially a shortcut for doing the whole packaging step in a linux VM.  For an example, see https://github.com/toolness/walden-journal-extractor/commit/f5191c98ae420f2405024c96dfd43c1fd781c1cc.

Obviously it's still _far_ from ideal, though.
