### ISSUE TITLE
Missing execute permission for Linux build

### ISSUE THREAD

**Issue by s-a** [maxogden/electron-packager#98]
Hi, the output for Linux builds does not contain the execute permission flag.

**Comment by kfranqueiro** [comment]
Can you provide [this information](https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md)?

The only way I can reproduce this issue is by building on Windows, which is likely trashing permissions from the Linux distributions of Electron. :/  On OS X and Linux the Linux executables seem to have proper permissions.

**Comment by s-a** [comment]
Sorry! This happens after grunt contrib copy job.
